- name: Download the Earlang Script
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
  
- name: Download rabbitmq repo 
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install Rabbit mq
  ansible.builtin.package:
    name: rabbitmq-server 
    state: present 

- name: enable and start rabbitmq 
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: yes  
    state: started 

- name: create rabbitmq user and password
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup('aws_ssm', '/roboshop/{{env}}/rabbitmq_user', region='us-east-1', decrypt=True )}}"
    password: "{{ lookup('aws_ssm', '/roboshop/{{env}}/rabbitmq_password', region='us-east-1', decrypt=True )}}"
    vhost: /
    configure_priv: .* 
    read_pri: .*  
    write_priv: .* 
    state: present
