- name: disable default mysql
  ansible.builtin.command: dnf module disable mysql -y 

- name: copy mysql.repo file
  ansible.builtin.copy: 
    src: mysql.repo 
    dest: /etc/yum.repos.d/mysql.repo

- name: install mysql-community-server
  ansible.builtin.package:
    name: mysql-community-server
    state: present 

- name: enable and start mysql 
  ansible.builtin.service: 
    name: mysqld 
    enabled: yes  
    state: started 

- name: Setup root password 
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
