- name: app-setup
  ansible.builtin.import_role: 
    name: common
    tasks_from: app-setup

- name: go setup
  ansible.builtin.import_role: 
    name: common
    tasks_from: go-setup

- name: systemd setup
  ansible.builtin.import_role: 
    name: common
    tasks_from: systemd