- name: stop {{component}}
  tags:
    - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags:
    - deployment
  ansible.builtin.file:
    path: /app/*
    state: absent

- name: Create App Directory
  tags:
    - deployment
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download {{component}} Application
  tags:
    - deployment
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp/ 

- name: "Unzip the {{component}}"
  tags:
    - deployment
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes

- name: Install dependencies
  tags:
    - deployment
  ansible.builtin.command: npm install 
  args:
    chdir: /app

- name: start {{component}}
  tags:
    - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted



