- name: copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client
  ansible.builtin.shell: dnf install mongodb-org-shell -y

- name: get the catalogue entries count
  ansible.builtin.command: mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: products_count
  when: component == "catalogue"

- name: get the user entries count
  ansible.builtin.command: mongo --host {{MONGODB_HOST}} --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: users_count
  when: component == "user"

- name: Print the catalogue count
  ansible.builtin.debug:
    msg: "product count is: {{products_count}}"
  when: component == "catalogue" 

- name: Print the users count
  ansible.builtin.debug:
    msg: "users count is: {{users_count}}"
  when: component == "user" 

- name: load catalogue data into mongodb
  ansible.builtin.shell: mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js
  when: products_count.stdout == "0" and component == "catalogue"
  ignore_errors: true 

- name: load user data into mongodb
  ansible.builtin.shell: mongo --host {{MONGODB_HOST}} < /app/schema/{{component}}.js
  when: users_count.stdout == "0" and component == "user" 
  ignore_errors: true

