- name: Install mysql client 
  ansible.builtin.dnf: 
    name: mysql 
    state: present

- name: check cities schema exist or not
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME= 'cities'"
  register: schema 

- name: print output 
  ansible.builtin.debug:    
    msg: "schema output: {{schema}}" 

- name: loading shipping data into mysql 
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/schema/shipping.sql # We haev to use builtin.shell command as it will login and load the contenets builtin.command will not work
  when: schema.stdout == "0"
